defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: wesleyzhang
  password:
  host: localhost

development:
  <<: *defaults
  database: blog_development

test: &test
  <<: *defaults
  database: blog_test

production:
  <<: *defaults

cucumber:
  <<: *test